import { ArrowUpRight } from 'lucide-react';
const roles = [
  { company: 'CME-Pro', initials: 'CP', role: 'AI Software Engineer', kind: 'Freelance contractor', date: 'MAR 2026 — PRESENT', text: 'Building internal tooling for agentic workflows and retrieval-augmented customer support, connecting AI capabilities to everyday operations.', tags: ['n8n', 'Docker', 'AWS', 'Gemini'], current: true },
  { company: 'Monark Inc.', initials: 'M', role: 'Junior Full Stack Developer', kind: 'Toronto, Canada', date: 'AUG 2025 — FEB 2026', text: 'Led a React Native and Expo mobile rebuild for a platform serving 1,500+ users and 30+ business customers. Built navigation across 80+ screens, including tabs, drawers, and modals.', tags: ['React Native', 'Expo', 'TypeScript'] },
  { company: 'NUS College Club', initials: 'NC', role: 'Deputy Director of Technologies', kind: 'Student leadership', date: '2024 — 2025', text: 'Contributed to the student community through technology leadership, working with others to support the needs of NUS College.', tags: ['Technical leadership', 'Collaboration'] },
];
export default function Experience() {
  return <section id="experience" className="experience-section"><div className="shell section"><div className="section-heading"><div><p className="eyebrow">02 / THE JOURNEY SO FAR</p><h2>Learning by <span className="serif">building.</span></h2></div><a className="text-link" href="/Jaymeson_Koh_Resume.pdf" target="_blank" rel="noreferrer">The full résumé <ArrowUpRight size={17} /></a></div><div className="experience-list">{roles.map(role => <article className="experience-row" key={role.company}><div className="experience-date">{role.current && <span className="current-label"><span className="status-dot" />CURRENTLY</span>}<span>{role.date}</span></div><div className="company-icon">{role.initials}</div><div className="experience-role"><h3>{role.company}</h3><p>{role.role}</p><span>{role.kind}</span></div><div className="experience-summary"><p>{role.text}</p><div className="tags">{role.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></div></section>;
}
