import { useState } from 'react';
import { ArrowUpRight, Database, GitBranch, ListChecks, Terminal } from 'lucide-react';

const projects = [
  { id: 'sqlancer', title: 'SQLancer benchmarking', type: 'Web', year: '2025', kicker: 'MAKING COMPLEX SYSTEMS LEGIBLE', description: 'A clearer view into database testing. Led a six-person frontend team building a platform for exploring SQLancer benchmarks.', tags: ['Next.js', 'TypeScript', 'React'], detail: 'Frontend team lead · Team of 6' },
  { id: 'internbuddy', title: 'InternBuddy', type: 'Desktop', year: '2024', kicker: 'LESS ADMIN. MORE MOMENTUM.', description: 'A desktop companion for the internship hunt. Led a five-person team building tools to organise contacts and keep applications moving.', tags: ['Java', 'JavaFX', 'JUnit'], detail: 'Team lead · Team of 5', url: 'https://github.com/AY2425S1-CS2103T-T09-1/tp', label: 'View source' },
  { id: 'fintrack', title: 'FinTrack', type: 'Mobile', year: '2024', kicker: 'SMALL HABITS, CLEARER FINANCES', description: 'A personal finance app built with a teammate, bringing expense tracking and everyday money management to mobile.', tags: ['React Native', 'Expo', 'Firebase'], detail: 'Co-developer · Team of 2' },
  { id: 'tictactoe', title: 'Ultimate Tic-Tac-Toe AI', type: 'AI', year: '2025', kicker: 'THINKING A FEW MOVES AHEAD', description: 'A game-playing agent that explores search, heuristics, and the trade-offs behind choosing a good move efficiently.', tags: ['Python', 'Minimax', 'Alpha-beta pruning'], detail: 'AI & algorithm design' },
];
const filters = ['All work', 'Web', 'Mobile', 'Desktop', 'AI'];

function ProjectArtwork({ id }: { id: string }) {
  if (id === 'sqlancer') return <div className="project-art art-sql" aria-hidden="true"><div className="diagram-heading"><Database size={18} /><span>BENCHMARK EXPLORER</span><span className="diagram-dot" /></div><div className="query-line"><span>SELECT</span> a better perspective<span className="cursor-line">_</span></div><div className="database-flow"><div><Database size={23} /><span>Database</span></div><i /><div><Terminal size={23} /><span>Test engine</span></div><i /><div><GitBranch size={23} /><span>Insights</span></div></div><div className="art-bottom"><span>RUN → COMPARE → UNDERSTAND</span><span>01</span></div></div>;
  if (id === 'internbuddy') return <div className="project-art art-intern" aria-hidden="true"><div className="mini-window"><div className="window-bar"><span /><span /><span /><b>internbuddy</b></div><div className="organiser"><div className="organiser-sidebar"><ListChecks size={25} /><i /><i /><i /></div><div className="organiser-body"><span className="mini-label">YOUR NEXT CHAPTER</span><strong>A little more organised.</strong>{['Find the opportunity', 'Make the connection', 'Take the next step'].map((text, i) => <div className="task-line" key={text}><span>{String(i + 1).padStart(2, '0')}</span>{text}<span>↗</span></div>)}</div></div></div><span className="art-bottom">FROM APPLICATION TO OPPORTUNITY</span></div>;
  if (id === 'fintrack') return <div className="project-art art-fin" aria-hidden="true"><div className="fin-orbit" /><div className="fin-caption"><span className="mini-label">FINTRACK</span><strong>Make room<br />for what<br /><em>matters.</em></strong></div><div className="phone-outline"><div className="phone-speaker" /><span className="mini-label">YOUR MONEY, AT A GLANCE</span><div className="donut"><span>Everyday<br /><strong>balance.</strong></span></div><div className="phone-row"><span className="phone-icon">↗</span><span>Track spending<i /></span></div><div className="phone-row"><span className="phone-icon">+</span><span>Build a habit<i /></span></div></div></div>;
  return <div className="project-art art-game" aria-hidden="true"><span className="mini-label">SEARCH. EVALUATE. DECIDE.</span><div className="game-grid">{['×', '○', '', '', '×', '○', '○', '', '×'].map((mark, i) => <span className={mark === '×' ? 'cross' : ''} key={i}>{mark}</span>)}</div><div className="art-bottom"><span>ONE MOVE. MANY POSSIBILITIES.</span><span>04</span></div></div>;
}

export default function Projects() {
  const [filter, setFilter] = useState('All work');
  const visible = projects.filter(project => filter === 'All work' || project.type === filter);
  return <section id="projects" className="section shell" aria-labelledby="projects-title"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2 id="projects-title">Ideas made <span className="serif">tangible.</span></h2></div><p>A few things I’ve built with good people,<br className="desktop-break" /> plenty of questions, and a lot of iteration.</p></div>
    <div className="project-toolbar"><div className="project-filters" role="group" aria-label="Filter projects">{filters.map(item => <button key={item} onClick={() => setFilter(item)} aria-pressed={filter === item} className={filter === item ? 'active' : ''}>{item}</button>)}</div><span className="project-count" aria-live="polite">{String(visible.length).padStart(2, '0')} PROJECT{visible.length === 1 ? '' : 'S'}</span></div>
    <div className="project-grid">{visible.map(project => <article className="project-card" key={project.id}><ProjectArtwork id={project.id} /><div className="project-meta"><span>{project.type} development</span><span>{project.year}</span></div><div className="project-title-row"><h3>{project.title}</h3>{project.url && <a className="project-arrow" href={project.url} target="_blank" rel="noreferrer" aria-label={`${project.label}: ${project.title}`}><ArrowUpRight size={22} /></a>}</div><p className="project-description">{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><p className="project-detail">{project.detail}</p></article>)}</div><p className="artwork-note">Project illustrations are conceptual, not application screenshots.</p>
  </section>;
}
